title       = "chucknorris"
baseURL     = "https://chucknorris-cli.tamnd.com/"
description = "A command line for chucknorris."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/chucknorris-cli"
